// Builds main.js from src/ with no dependencies: the sources are plain scripts, concatenated
// in load order, with dashboard.js wrapped as an async function so it can be re-run per render.
//
//   node scripts/build.mjs                      write main.js
//   node scripts/build.mjs --out <plugin dir>   also copy main.js, manifest.json, styles.css there
//   node scripts/build.mjs --watch --out <dir>  rebuild and copy on every change in src/
//   node scripts/build.mjs --example            write example-vault/ with the plugin installed
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, watch, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import vm from "node:vm";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const option = name => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : null;
};
const read = path => readFileSync(join(root, path), "utf8");
const RELEASE_FILES = ["main.js", "manifest.json", "styles.css"];

export function bundle() {
  const { version } = JSON.parse(read("manifest.json"));
  return [
    `/* OneDesk ${version} · generated by scripts/build.mjs from src/ — edit those files, not this one. */`,
    "",
    "// ── src/lifelog-timeline.js ──",
    read("src/lifelog-timeline.js"),
    "// ── src/literature-core.js ──",
    read("src/literature-core.js"),
    "// ── src/english-patterns.js ──",
    read("src/english-patterns.js"),
    "// ── src/sample-vault.js ──",
    read("src/sample-vault.js"),
    "// ── src/dashboard.js ──",
    "async function runDashboard(dv, app, DB26_CONFIG, Notice) {",
    read("src/dashboard.js"),
    "}",
    "",
    "// ── src/main.js ──",
    read("src/main.js"),
  ].join("\n");
}

export function sampleFiles(now = new Date()) {
  const context = { now };
  vm.runInNewContext(read("src/literature-core.js") + "\n" + read("src/sample-vault.js") + "\nresult = onedeskSampleFiles(now);", context);
  return context.result;
}

function build(outDir) {
  writeFileSync(join(root, "main.js"), bundle());
  if (outDir) {
    mkdirSync(outDir, { recursive: true });
    for (const f of RELEASE_FILES) copyFileSync(join(root, f), join(outDir, f));
  }
  console.log(`[${new Date().toLocaleTimeString()}] built main.js${outDir ? " → " + outDir : ""}`);
}

function writeExampleVault() {
  const vault = join(root, "example-vault");
  rmSync(vault, { recursive: true, force: true });
  for (const [path, content] of Object.entries(sampleFiles())) {
    mkdirSync(dirname(join(vault, path)), { recursive: true });
    writeFileSync(join(vault, path), content);
  }
  const plugins = join(vault, ".obsidian", "plugins");
  build(join(plugins, "onedesk"));
  writeFileSync(join(vault, ".obsidian", "community-plugins.json"), JSON.stringify(["dataview", "onedesk"], null, 2));
  if (!existsSync(join(plugins, "dataview"))) {
    console.log("example-vault: install and enable Dataview in it before opening OneDesk.");
  }
  console.log(`example-vault written: ${vault}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const out = option("--out");
  if (args.includes("--example")) {
    writeExampleVault();
  } else {
    build(out);
    if (args.includes("--watch")) {
      let timer = null;
      for (const dir of ["src", "."]) {
        watch(join(root, dir), (_event, name) => {
          if (dir === "." && !["styles.css", "manifest.json"].includes(name)) return;
          clearTimeout(timer);
          timer = setTimeout(() => build(out), 150);
        });
      }
      console.log("watching src/, styles.css and manifest.json …");
    }
  }
}
